Add DigiD.nl (#2808)
* Add DigiD

* Remove hardware to Fix Travis Error

No YML tag if it is set to 'no'.

ERROR: "1. DigiD: 'false': not matched to pattern /true/."

* Removed hardware line, because of Travis error.
Added information about exceptions of DigiD 2FA.

* Removed accidental blank line

* Rewrote description.